package com.example.dataService.controller;

import com.example.dataService.entity.User;
import com.example.dataService.jpaRepoisitory.UserRepository;
import com.example.dataService.mapper.UserMapper;
import com.example.entity.TestUser;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class TestController {

    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private UserRepository userRepository;

    @Autowired
    private UserMapper userMapper;

    @RequestMapping("/user")
    public String user(){
        User user = new User();
//        user.setId(7);
        user.setEmail("1178376362@11.com");
        user.setName("evins");
        userRepository.save(user);
        return user.toString();
    }

    @RequestMapping("/get/{id}")
    public String getById(@PathVariable int id){
        User user = userMapper.getById(id);
        return user.toString();
    }

    @RequestMapping("/selectById/{id}")
    public String selectById(@PathVariable int id){
        User user = userMapper.selectById(id);
        return user.toString();
    }

    @RequestMapping("/test")
    public String test(){
        TestUser testUser = new TestUser(7,"evins-testuser");
        System.out.println("testUser="+testUser.toString());
        return "test data service";
    }
}
